### ISSUE TITLE
Error analyzing component when it is imported indirectly

### ISSUE THREAD

**Issue by stogle** [ipatalas/ngComponentUtility#10] opened 2017-05-28 16:46 UTC
If an index.ts file registers a component that it has imported from another index.ts file (rather than directly from the file that contains the definition), the following error is logged:

> [ngComponents] There was an error analyzing .\src\index.ts.
> Please report this as a bug and include failing file if possible (remove or change sensitive data).
>
> This component configuration type is not supported yet - please raise an issue and provide an example

For example, if I have the following three files I get the error:

index.ts:
```
import {
    Test1,
    Test2
} from "./components";

angular.module("components", [])
    .component("test1", new Test1())
    .component("test2", new Test2());
```
components/index.ts:
```
export {Test1} from "./test1.component.ts
export {Test2} from "./test2.component.ts
```
test1.component.ts (test2.component.ts would be similar):
```
import {Test1Controller} from "./test1.controller";

export class Test1 implements ng.IComponentOptions {
    public controller: ng.Injectable<ng.IControllerConstructor> = Test1Controller;
    public template: string = require("./test1.html");
}
```
If I change the import in the original index.ts as follows, it no longer produces the error:
```
import {Test1} from "./components/test1.component";
import {Test2} from "./components/test2.component";
```
I believe the error is occurring because `classDeclaration` is undefined at https://github.com/ipatalas/ngComponentUtility/blob/master/src/utils/component/componentParser.ts#L63. To fix it I guess you would need to look in imported files recursively until you find the class declaration.

PS This is the last type of error I am getting in the developer tools console (sorry I didn't report this at the same time as the previous two issues - it took me a little longer to figure it out). However, despite analyzing all my index files, the extension only seems to recognize 47 components, and I think I have 79 in my project. Do you have any suggestions as to how I could identify which components it didn't recognize and pinpoint why? Some sort of verbose logging option would be ideal, but I'm prepared to run the extension in a debugger if you could point me in the right direction (I have not worked with VS Code extensions before).

**Comment by ipatalas** [comment] 2017-05-28 21:11
Ok. I can see multiple problems here. I will probably split that to smaller independent issues later on when I start working on them but for now let's stick to this one.

You're right about making a recursive look up until a declaration is found but that's only one thing that didn't work here.

I see at least two other issues here:

1. Extension doesn't yet support imports from `"./components"` which is an implicit `components/index.ts`. At the moment it's trying to import `./components.ts` which is why it's failing.

2. Multiple chained component registrations are not supported as well so this:
   ```TS
   angular.module("components", [])
       .component("test1", new Test1())
       .component("test2", new Test2());
   ```
   will only capture last registration. It might be the reason why it doesn't recognize some of your components.

Based on this short research I see 3 different issues here 😉 


Regarding your problem with recognizing all the components I already mentioned one of possible problems above. Can't quickly point different things that might not have worked as they should. 
There is no verbose logging so far. I'm already one leg in bed so I will just add it to my list and meanwhile I can try to help you figure it out on your own.

Running an extension is really easy. Actually it should be enough if you just clone the repository, `npm install` packages and then run the extension using F5. 
It should open another instance of VSCode which will override the extension installed from marketplace with the one run from code so you don't have to uninstall it before debugging. It just works seamlessly. 
You should then open the folder with your Angular project in that instance and switch to a TS/HTML file so that the extension will get activated (soon to be changed to auto-detect Angular project automatically).
Having that you can set breakpoints in extension in first instance of VSCode and just click `Refresh Angular components` from status bar to initiate components discovery. 
What's really cool is that if you make any changes in the code of the extension (more `console.log`s for instance) you just save the file (it should automatically transpile TS to JS) and hit Ctrl-R (`Reload window` command in case you're not running on Windows) in the instance where the debugged extension is running. There is no need to restart the application again. It's really a huge time saver for me. I only restart when debugger starts to misbehave.

For starters I would suggest to log the components that were processed successfully. To do so just add `console.log(component.name)` in this line: https://github.com/ipatalas/ngComponentUtility/blob/master/src/utils/component/componentParser.ts#L39 (just inside the `if`). That should give you the list of components which succeeded. From that you should be able to find out which of them are missing on the list. If you find one just go the where it's registered (`[...].component('name', new Something())`) and check if it's not a chained registration. If it's not then perhaps we have another case which is not handled yet. 
Please let me know then and provide an example so that I can reproduce the issue.

Thanks again for yet another great report. You're doing really good job here 👍

**Comment by stogle** [comment] 2017-05-30 03:20
I didn't realize this was actually multiple issues! Thanks for the guidance on debugging the extension. It sounds pretty simple so I will give it a go soon, but I think you are right that chained component registration accounts for most of my "missing" components.

Happy to help with the bug reports, and thank you for all the prompt responses.

**Comment by ipatalas** [comment] 2017-06-01 20:34
As I mentioned earlier I split this issue into 3 smaller ones because they are not related.
Feel free to track them - links just above this comment. Closing this one to avoid duplicates.

**Closed by ipatalas** 2017-06-01 20:34 UTC
Labels: bug
