### ISSUE TITLE
Member completion doesn't work.

### ISSUE THREAD

**Issue by sergxp** [ipatalas/ngComponentUtility#20] opened 2018-01-26 17:19 UTC
Components work fine with all the autocomplete and peek definition, but I'm not getting any properties to show up.
Here's what I'm getting in the console.

```
[Extension Host] [ngComponents] Controller stats [files=191, glob=4.54 s, parse=413 ms, analyze=54 ms, total=5.01 s]
[Extension Host] [ngComponents] Controller for spinner not found (member completion and Go To Definition for this component will not work) console.ts:123 
[Extension Host] [ngComponents] Controller for insighttexteditor not found (member completion and Go To Definition for this component will not work) console.ts:123 
[Extension Host] [ngComponents] Controller for assessorincomeactivity8card not found (member completion and Go To Definition for this component will not work)console.ts:123 
[Extension Host] [ngComponents] Controller for assessorincomeactivity7card not found (member completion and Go To Definition for this component will not work) console.ts:123 
[Extension Host] [ngComponents] Controller for assessorincomeactivity6card not found (member completion and Go To Definition for this component will not work)


```

**Comment by ipatalas** [comment] 2018-01-26 18:04
Hi, please show me the definition of one of these components.

**Comment by sergxp** [comment] 2018-01-26 19:18
```
module settings.Customer {
  'use strict';
  angular.module('settings.customer')
    .component('settingscustomercard',
      {
        templateUrl: 'app/settings/customer/list/card/settings.customer.list.card.html',
        controller: 'settingsCustomerListCardController',
        bindings: {
          customer: '<'
        }
      });
}
```

**Comment by sergxp** [comment] 2018-01-26 19:19
Here is the controller

```
module settings.Customer {
  'use strict';

  class CustomerController {
    customer: ICustomer;
  }

  angular.module('settings.customer')
    .controller('settingsCustomerListCardController', CustomerController);
}
```

**Comment by ipatalas** [comment] 2018-01-26 22:24
Hmm, are you sure this one is failing too?

Got it copied to my test project and it works just fine. I don't see anything suspicious here as well. For the controller to be found it needs `controller` field specified which is the case here. It works if it's either a string like in your example or a class identifier directly so there is nothing wrong here.

Please share one of `spinner`, `insighttexteditor`. or `assessorincomeactivityXcard` which all fail according to the logs you provided. You can skip the logic of course. Just the component definition and the same for controller like above should be sufficient.

**Comment by sergxp** [comment] 2018-01-29 20:13
Here is insightTextEditor
```
module controls {
    'use strict';

    class TextEditorController {
        static $inject: string[] = ['richTextEditorService', '$scope'];

        insightModel: string;
        appendPoint: any;
        compileRan: boolean = false;
        containsMarkUp: boolean = false;
        randomId: number;
        timeOutId: number;
        textarea: boolean;
        placeholder: string;

        constructor(private richTextEditorService: controls.IRichTextEditorService,
            private $scope: any) { }

   angular.module('controls')
        .controller('textEditorController', TextEditorController)
        .directive('markupCheck', () => {

            function linkFn(scope, element, attrs, ngModel: ng.INgModelController) {
                scope.$ctrl.appendPoint = element[0];
                scope.$ctrl.$onInit();
            }

            return {
                require: 'ngModel',
                link: linkFn
            };
        });
}

```

**Comment by sergxp** [comment] 2018-01-29 21:25
here is the component for insightTextEditor
```

    module shared.layout {
        'use strict';
        angular.module('controls')
            .component('insighttexteditor',
            {
                templateUrl: 'src/app/controls/texteditor/controls.texteditor.html',
                controller: 'textEditorController',
                bindings: {
                    insightModel: '=',
                    textarea: '<',
                    placeholder: '@'
                }
            });
    }
```

**Comment by ipatalas** [comment] 2018-01-29 21:31
Great, I can reproduce it now. 
I'll try to look at it in upcoming week or so.

**Comment by sergxp** [comment] 2018-01-29 21:56
Great thank you

**Comment by ipatalas** [comment] 2018-02-02 18:35
Looks like the syntax to chain registrations on a module doesn't work (yet).
As a temporary solution before the fix is ready you could separate registrations as follows:
```JS
angular.module('controls').controller('textEditorController', TextEditorController);
angular.module('controls').directive('markupCheck', ...
```

**Comment by sergxp** [comment] 2018-02-02 20:32
I see you did a fix and it looks like I'm not getting as many "controller not found" messages, only a few. But it still does not show any intellisense on any properties. I just downloaded the master and replaced all files in the extension folder. Was that the correct way to update the extension or am I doing something wrong?

**Comment by ipatalas** [comment] 2018-02-02 20:40
It's not a proper way to do that. I'm not sure if it might be the reason for this, but please hold on for an official deployment.
Just working on it, but getting some unexpected errors. I did last deployment almost half year ago and seems like something has changed since then. It shouldn't take longer than an hour hopefully.

**Comment by ipatalas** [comment] 2018-02-02 21:18
What a bad luck today. Apart from new TypeScript throwing some new errors also my token to publish extensions has expired after a year. Nonetheless it's done!
You can update the extension via VS Code directly now. Actually it should happen automatically after you open VS Code. If it doesn't you can do that manually:
![image](https://user-images.githubusercontent.com/2623329/35755277-e4c46db8-0866-11e8-9d7a-ebe7b00c08ec.png)

**Comment by ipatalas** [comment] 2018-02-03 22:06
@sergxp does it work now?

**Comment by sergxp** [comment] 2018-02-06 20:34
Sorry for getting back so late, I tried uninstalling and reinstalling the extension. I'm not seeing any difference. 
![image](https://user-images.githubusercontent.com/28748653/35882751-cbfaa194-0b4a-11e8-9e82-da54e114bcaa.png)

**Comment by ipatalas** [comment] 2018-02-07 20:57
Hi,

well, that only makes it harder to guess what might be the issue.
First of all make sure it really got updated:
![image](https://user-images.githubusercontent.com/2623329/35940453-7a20773a-0c4f-11e8-8361-6f88c518027d.png)
It should say 0.7.2.

Next step would be to check if `insighttexteditor` is still on the list of "Controller for X not found".
If it's not then maybe the other controllers have different issue.
Please pick any of them (`archivedashboard`, `spinner`, `settingsdashboardcard`, etc.) and please show them here (both controller file and component for it with all the Angular registrations included) just like you did before.
I also see that the parsing time for your controllers is very high which I suppose mean that either you have very big controllers, many controllers in single file or just a lot of other code in files matching Controller glob pattern.
Describing your situation might give me a clue what's wrong.

**Comment by sergxp** [comment] 2018-02-07 21:14
I have double checked and the version is in fact 0.7.2. insightexteditor is not on the list anymore. The other controllers that are on the list are just components that don't implement any controllers. Maybe if I give you my folder structure it might help?

![image](https://user-images.githubusercontent.com/28748653/35941773-0492249a-0c19-11e8-91f9-da3e2763c8ac.png)

**Comment by sergxp** [comment] 2018-02-07 21:18
Here is an example of component definition working.
![image](https://user-images.githubusercontent.com/28748653/35941961-b37ab40e-0c19-11e8-90bc-4d264a063153.png)

But when I try it on the properties...
![image](https://user-images.githubusercontent.com/28748653/35942054-11454338-0c1a-11e8-84b5-be335d85ffa3.png)

**Comment by ipatalas** [comment] 2018-02-07 21:39
@sergxp what do you mean that those components don't implement any controller? Can you give an example of one?

**Comment by sergxp** [comment] 2018-02-07 21:52
![image](https://user-images.githubusercontent.com/28748653/35943485-d52cdbcc-0c1e-11e8-9f6a-2fa5d7a0e8c6.png)

**Comment by ipatalas** [comment] 2018-02-08 17:03
Ok. I think I know what's wrong now.

Let's take your first example first:
![image](https://user-images.githubusercontent.com/2623329/35986247-d71aa54c-0cf8-11e8-8642-36199bf1286d.png)
and then:
![image](https://user-images.githubusercontent.com/2623329/35986258-dc20de4e-0cf8-11e8-8967-d5cc302e7cdc.png)

If I get your intention correctly you meant to go to **currentLocation** property of **insightheader** component. If so then you should have clicked F12 (or Ctrl-Click) on the binding name instead of the value. 
I believe full line looks more like this:
```HTML
<insightheader current-location="$ctrl.currentLocation"></insightheader>
```
The cursor should be focused on `current-location` binding instead of its value.
Executing it on the value (`$ctrl.currentLocation`) has different meaning. It would go to currentLocation property of the containing component.
Why it doesn't go there is another story. Perhaps this controller is not defined or maybe something else. I would need more context to judge.

Regarding the other example:
![image](https://user-images.githubusercontent.com/2623329/35986592-bdf51646-0cf9-11e8-8d1f-6c69e85ad1e2.png)

This will work but since the controller is not defined it issues a warning about it. I didn't think about it earlier but now I see that I can easily distinguish whether the controller is not defined or it couldn't be found for any reason. The former situation shouldn't actually issue the warning.
Will do that in a minute, but this is gonna wait for something more before it's released :)

**Comment by sergxp** [comment] 2018-02-08 20:27
My intention was the latter. I wanted to see the definition of my current controller's property "currentLocation".  This is for a component called "studyquotaslist". Here is my implementation: 
![image](https://user-images.githubusercontent.com/28748653/35996250-a0528506-0cdb-11e8-8491-d3620a6e4513.png)
![image](https://user-images.githubusercontent.com/28748653/35996279-b61574ca-0cdb-11e8-8cfe-ce304a9e2eb3.png)
....
![image](https://user-images.githubusercontent.com/28748653/35996299-c3a15d66-0cdb-11e8-99b6-b4c68a1eab19.png)
![image](https://user-images.githubusercontent.com/28748653/35996321-d092b15a-0cdb-11e8-893a-da52297b1192.png)

But to your first point, ctrl clicking on the binding name current-location does nothing as well. Nor does peek definition and go to definition, all are non functional. The only thing that is functional is definitions of actual component names ie: <insightheader>

**Comment by ipatalas** [comment] 2018-02-08 21:47
Ok, that's getting difficult to debug remotely :)

Did my best to recreate the situation based on your screenshots, but it still works for me...
Please have a look at this: https://1drv.ms/u/s!AvGOEnwGkBeKgxI5G-5e8PMiqDWf

Unzip, open in VSCode and open **issue20.html**.

Try using Go To Definition on all `$ctrl.currentLocation` occurences. Let me know which of them work or not.
They all work for me so I might have missed something in some of these files. If you can try to adjust them so that the error can be reproduced and send it back then it would be great!

**Comment by sergxp** [comment] 2018-02-08 22:33
I confirm that it works with your folder structure, but when I use my folder structure, I get the same behavior as I described earlier. See if you can reproduce the issue. https://www.dropbox.com/s/4o77q2vjhrssv4u/issue20%28sergxp%29.zip?dl=0

**Comment by ipatalas** [comment] 2018-02-09 21:07
Ok, it indeed doesn't work with your example but there is an error there in **issue20Component.ts**
I changed the template path to `templateUrl: 'study/quotas/list/issue20.html'` to reflect the actual structure and it started working again.

**Comment by sergxp** [comment] 2018-02-12 16:12
So it does indeed like the issue is solved and it's just my folder strucutre that's the issue. You can change this issue to fixed. I am still having difficulty with making this work with my folder structure.
![image](https://user-images.githubusercontent.com/28748653/36106342-b0e6f25e-0fdc-11e8-83ca-d9a27472d11e.png)
My AngularJS resides in "app" and all of my SASS in "content" all of my templateUrl files begin with "app/.../../..." as soon as I change them to /src/app/.../.../" member intellisense starts working. But that would break my angular builds. Is there any workarounds for this?

PS: when I did change it to /src and played around with it a little, ctrl hover and peek definition worked great except for looking at object properties didn't show any information. Also when starting to type {{ i got an option for $ctrl but after that I did not receive any members. Funny enough though once I manually typed a member and ctrl hovered of it, it showed me correct intellisense.

**Comment by ipatalas** [comment] 2018-02-12 19:53
Ok, closing this one and opened a new one at #22 to discuss this as a separate issue.

**Closed by ipatalas** 2018-02-12 19:53 UTC
Labels: bug
